language: python
python: 3.6
sudo: false

env:
- TOXENV=py27-dj12
- TOXENV=py27-dj13
- TOXENV=py27-dj14
- TOXENV=py27-dj15
- TOXENV=py27-dj16
- TOXENV=py27-dj17
- TOXENV=py27-dj18
- TOXENV=py27-dj19
- TOXENV=py27-dj110
- TOXENV=py27-dj111

- TOXENV=py33-dj15
- TOXENV=py33-dj16
- TOXENV=py33-dj17
- TOXENV=py33-dj18

- TOXENV=py34-dj17
- TOXENV=py34-dj18
- TOXENV=py34-dj19
- TOXENV=py34-dj110
- TOXENV=py34-dj111
- TOXENV=py34-dj20

- TOXENV=py35-dj19
- TOXENV=py35-dj110
- TOXENV=py35-dj111
- TOXENV=py35-dj20
- TOXENV=py35-djmaster

- TOXENV=pypy-dj12
- TOXENV=pypy-dj13
- TOXENV=pypy-dj14
- TOXENV=pypy-dj15
- TOXENV=pypy-dj16
- TOXENV=pypy-dj17
- TOXENV=pypy-dj18
- TOXENV=pypy-dj19
- TOXENV=pypy-dj110
- TOXENV=pypy-dj111

install:
- pip install -U tox

script: tox
