language: python
python: 3.6
sudo: false

matrix:
  include:
    - env: TOXENV=py36-dj18,py36-dj111,py36-dj20,coverage,flake
    - env: TOXENV=py36-djmaster
    - python: 3.5
      env: TOXENV=py35-dj18,py35-dj111,py35-dj20
    - python: 3.4
      env: TOXENV=py34-dj18,py34-dj111,py34-dj20
    - python: 2.7
      env: TOXENV=py27-dj18,py27-dj111

before_script:
- pip install tox

script: tox -e $TOXENV
