name: Lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django coverage flake8
    - name: Run flake
      run: flake8 widget_tweaks
    - name: Calculate coverage
      run: |
        coverage run runtests.py
        coverage report
